on:
  push:
    branches:
      - main

jobs:
  docs:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Generate project documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tool Versions
        uses: marocchino/tool-versions-action@v1
        id: versions

      - name: Sets up an Erlang/OTP environment
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ steps.versions.outputs.erlang }}
          elixir-version: ${{ steps.versions.outputs.elixir }}

      - name: Build docs
        uses: lee-dohm/generate-elixir-docs@v1.0.1

      - name: Publish to Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          deploy_key: ${{ secrets.DOCS_DEPLOY_KEY }}
          publish_dir: ./doc
          publish_branch: gh-pages